print("Zuhriansyah Abdillah")
print("2310432020")
print()
from termcolor import cprint
for i in range (5):
    cprint("                                                      ", "white", "on_blue")
print()
print()
print(" ", end = " ")
cprint(" "*2, "white", "on_blue", end = "       ")
cprint(" "*2, "white", "on_blue", end = "     ")
cprint(" "*2, "white", "on_blue", end = "       ")
cprint(" "*8, "white", "on_blue", end = "          ")
cprint(" "*2, "white", "on_blue", end = "       ")
print()
print(" ", end = "  ")
cprint(" "*2, "white", "on_blue", end = "     ")
cprint(" "*2, "white", "on_blue", end = "      ")
cprint(" "*2, "white", "on_blue", end = "      ")
cprint(" "*2, "white", "on_blue", end = "               ")
cprint(" "*2, "white", "on_blue", end = " ")
cprint(" "*2, "white", "on_blue", end = "       ")
print()
print(" ", end = "   ")
cprint(" "*2, "white", "on_blue", end = "   ")
cprint(" "*2, "white", "on_blue", end = "       ")
cprint(" "*2, "white", "on_blue", end = "       ")
cprint(" "*6, "white", "on_blue", end = "         ")
cprint(" "*2, "white", "on_blue", end = "   ")
cprint(" "*2, "white", "on_blue", end = "       ")
print()
print(" ", end = "    ")
cprint(" "*2, "white", "on_blue", end = " ")
cprint(" "*2, "white", "on_blue", end = "        ")
cprint(" "*2, "white", "on_blue", end = "             ")
cprint(" "*2, "white", "on_blue", end = "      ")
cprint(" "*2, "white", "on_blue", end = " ")
cprint(" "*3, "white", "on_blue", end = " ")
cprint(" "*2, "white", "on_blue", end = "       ")
print()
print(" ", end = "     ")
cprint(" "*2, "white", "on_blue", end = "          ")
cprint(" "*2, "white", "on_blue", end = "      ")
cprint(" "*7, "white", "on_blue", end = "       ")
cprint(" "*2, "white", "on_blue", end = "       ")
cprint(" "*2, "white", "on_blue")
print()
print()
for i in range (5):
    cprint("                                                      ", "white", "on_yellow")
